theme: jekyll-theme-midnight

plugins:
  - jekyll-feed

title: PretensT
description: >
  Tensegrity is a special kind of structure made of push and pull.
email: pretenst@gmail.com
app_url: /app/
lab_url: /lab/
github:
  repository_url: https://github.com/elastic-interval/tensegrity-lab
  repository_name: tensegrity-lab
